eureka:
  instance:
    prefer-ip-address: true      # registers IP instead of hostname

  client:
    register-with-eureka: true   # tells this app to register itself with Eureka
    fetch-registry: true         # tells this app to fetch other registered services
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
